### ISSUE TITLE
SignUp: improve error messages

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#113]
As we (from what I understood) can't feedback more specific errors we should adapt the error message to cover more than just the username.

In this case the username should've been okay - just the email is already in use.

![image](https://cloud.githubusercontent.com/assets/10120609/23061165/06a2ad0c-f501-11e6-9198-8c78752c2852.png)

**Comment by BonsaiOfHappiness** [comment]
Should probably do all the messaging/alerts in one go at the end

**Comment by nhaesler** [comment]
Nope. We do get specific feedback for username and email. That username must've been taken. I chose to give the feedback there, because I don't think the user user should have to go back to the first step. Ideally we would give instant feedback on every field, but if we're using alert boxes I would do it like this.

**Comment by BonsaiOfHappiness** [comment]
Yes, you're right. The username was indeed taken. However, I seem to be able to signup more than once via an email (if it's not confirmed?). At least I don't get an error message for using the same email address again and even get into the game.

**Comment by nhaesler** [comment]
That's the server's doing and seems to be by design. Actually, when using the api call for email validation, it can answer with other-already-taken, which means that someone else already activated that email for their account.

**Comment by BonsaiOfHappiness** [comment]
Alright, that's fine then :)
